name: Render tutorial
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  render-tutorial:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
      - uses: r-lib/actions/setup-renv@v2

      - name: Cache across tutorial builds
        uses: actions/cache@v3
        with:
          path: |
            tutorial_cache
            tutorial_files
          key: cache

      - name: Render the README
        run: |
          rmarkdown::render(
            "README.md", output_format = "html_document",
            output_file = "index.html"
          )
        shell: Rscript {0}

      - name: Render the tutorial
        run: |
          rmarkdown::render("tutorial.Rmd")
        shell: Rscript {0}

      - name: Upload tutorial
        uses: actions/upload-artifact@v2
        with:
          name: tutorial
          retention-days: 5
          path: |
            index.html
            tutorial.html
